#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: migration
#  namespace: liferay
#spec:
#  replicas: 2
#  selector:
#    matchLabels:
#      app: migration
#  template:
#    metadata:
#      labels:
#        app: migration
#    spec:
#      containers:
#      - name: migration
#        image: jairoba/liferayapp:v1.0
#        imagePullPolicy: Always
#        ports:
#        - containerPort: 80

#### Mariadb 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
  namespace: liferay
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration
  namespace: liferay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: migration
  template:
    metadata:
      labels:
        app: migration
    spec:
      containers:
      - name: migration
        image: jairoba/liferayapp:v1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_HOST
          value: "mariadb.liferay.svc.cluster.local"
          #value: "mariadb"
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_DATABASE
          value: "test"
        - name: MYSQL_USER
          value: "test"
        - name: MYSQL_PASSWORD
          value: "test"
        - name: MYSQL_ROOT_PASSWORD
          value: "test"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
  namespace: liferay
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:5.5
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "test"
        - name: MYSQL_DATABASE
          value: "test"
        - name: MYSQL_USER
          value: "test"
        - name: MYSQL_PASSWORD
          value: "test"
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: db-storage
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: db-data

# SERVICE mariaDB
---

apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: liferay
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mariadb