apiVersion: apps/v1
kind: Deployment
metadata:
  name: migration
  namespace: liferay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: migration
  template:
    metadata:
      labels:
        app: migration
    spec:
      containers:
      - name: migration
        image: jairoJR-1/app:latest
        ports:
        - containerPort: 80