apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mariadb:5.5
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "test"
        - name: MYSQL_DATABASE
          value: "test"
        - name: MYSQL_USER
          value: "test"
        - name: MYSQL_PASSWORD
          value: "test"

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-service
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: db

