apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - port: {{ .Values.database.containerPort }}
    targetPort: {{ .Values.database.containerPort }}
  selector:
    app: mariadb