apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appService.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: migration
  ports:
    - protocol: TCP
      port: {{ .Values.appService.port }}
      targetPort: {{ .Values.appService.targetPort }}
  type: {{ .Values.appService.type }}
